image: python:3.10

stages:
  - tests
  - code_formatting
  - code_coverage
  - build

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

Unit test:
  stage: tests
  script:
    - poetry run pytest

Code formatting:
  stage: code_formatting
  script:
    - poetry run black . --check

Code Coverage:
  stage: code_coverage
  script:
    - poe poe_test

Docker Build:
  image: docker
  services:
    - docker:dind
  stage: build
  before_script: []
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE